# ── prometheus.yml ───────────────────────────────────────────────
# Tells Prometheus where to scrape metrics from

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'seg_fastapi'
    static_configs:
      - targets: ['seg_fastapi':8001]