services:
  - type: web
    name: customer-segmentation-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://martin:martin123@localhost:5432/segmentation_db

databases:
  - name: segmentation-db
    databaseName: segmentation_db
    user: martin
    plan: free